# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Big Data Real-Time Analytics com Python e Spark</font>

# <font color='blue'>Capítulo 2</font>

# <font color='blue'>Exercício</font>

Dados obtidos do Portal Brasileiro de Dados Abertos:
http://dados.gov.br/dataset/cidades-digitais

O projeto Cidades Digitais foi planejado para modernizar a gestão e ampliar o acesso ao serviço público, bem como promover o desenvolvimento dos municípios brasileiros através da tecnologia.

# Group By e Reshape

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html

In [3]:
import numpy as np
import pandas as pd

In [4]:
cidadesDigitais = pd.read_csv('cidades_digitais.csv', sep = ';', encoding = 'latin-1')

In [5]:
cidadesDigitais.head()

,UF,CIDADE,IBGE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,1200609,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,2702405,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,2702553,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,1300300,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,1300607,39484,"844.586,48",Sem Previsão,12,0

In [8]:
cidadesDigitais

,UF,CIDADE,IBGE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,1200609,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,2702405,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,2702553,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,1300300,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,1300607,39484,"844.586,48",Sem Previsão,12,0
...,...,...,...,...,...,...,...,...
333,SP,Vargem Grande do Sul,3556404,41807,"1.525.640,54",Sem Previsão,47,0
334,TO,Paraíso do Tocantins,1716109,49076,"1.872.693,90",Sem Previsão,49,0
335,TO,Ponte Alta do Bom Jesus,1717800,4649,"251.266,44",Sem Previsão,9,"23.969,90"
336,TO,Porto Nacional,1718204,52182,"1.101.168,76",Sem Previsão,61,0
337,TO,São Miguel do Tocantins,1720200,11597,"592.549,70",Sem Previsão,20,0

In [7]:
cidadesDigitais.count()

UF                      338
CIDADE                  338
IBGE                    338
POPULAÇÃO               338
VALOR_TOTAL_PREVISTO    338
STATUS                  338
PONTOS_ATENDIDOS        338
VALOR_INVESTIDO         338
dtype: int64

In [18]:
del cidadesDigitais['IBGE']

In [9]:
# Aplicando Group By
cidadesUF_1 = cidadesDigitais.groupby('UF')

In [10]:
type(cidadesUF_1)

pandas.core.groupby.generic.DataFrameGroupBy

In [11]:
cidadesUF_1.groups

{'AC': Int64Index([0], dtype='int64'),
 'AL': Int64Index([1, 2], dtype='int64'),
 'AM': Int64Index([3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64'),
 'AP': Int64Index([12, 13, 14, 15, 16, 17], dtype='int64'),
 'BA': Int64Index([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
             35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
            dtype='int64'),
 'CE': Int64Index([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
             68, 69, 70, 71, 72, 73, 74, 75, 76],
            dtype='int64'),
 'DF': Int64Index([77], dtype='int64'),
 'ES': Int64Index([78, 79, 80, 81], dtype='int64'),
 'GO': Int64Index([82, 83, 84, 85, 86, 87, 88, 89, 90, 91], dtype='int64'),
 'MA': Int64Index([ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
             105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117],
            dtype='int64'),
 'MG': Int64Index([118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
             131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
             144, 145],
            dtype='int64'),
 'MS': Int64Index([146, 147, 148], dtype='int64'),
 'MT': Int64Index([149, 150, 151, 152], dtype='int64'),
 'PA': Int64Index([153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
             166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176],
            dtype='int64'),
 'PB': Int64Index([177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
             190, 191, 192, 193, 194],
            dtype='int64'),
 'PE': Int64Index([195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
             208, 209, 210],
            dtype='int64'),
 'PI': Int64Index([211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
             224, 225, 226, 227, 228],
            dtype='int64'),
 'PR': Int64Index([229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
             242, 243, 244, 245],
            dtype='int64'),
 'RJ': Int64Index([246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
             259, 260],
            dtype='int64'),
 'RN': Int64Index([261, 262, 263, 264, 265, 266, 267, 268, 269], dtype='int64'),
 'RO': Int64Index([270, 271], dtype='int64'),
 'RR': Int64Index([272], dtype='int64'),
 'RS': Int64Index([273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
             286, 287, 288],
            dtype='int64'),
 'SC': Int64Index([289, 290, 291, 292, 293, 294], dtype='int64'),
 'SE': Int64Index([295, 296, 297, 298], dtype='int64'),
 'SP': Int64Index([299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
             312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
             325, 326, 327, 328, 329, 330, 331, 332, 333],
            dtype='int64'),
 'TO': Int64Index([334, 335, 336, 337], dtype='int64')}

In [12]:
cidades_UF1_df =pd.DataFrame(cidadesUF_1); cidades_UF1_df

     0                                                  1
0   AC     UF    CIDADE     IBGE  POPULAÇÃO VALOR_TOTA...
1   AL     UF              CIDADE     IBGE  POPULAÇÃO ...
2   AM      UF             CIDADE     IBGE  POPULAÇÃO ...
3   AP      UF            CIDADE     IBGE  POPULAÇÃO V...
4   BA      UF                     CIDADE     IBGE  PO...
5   CE      UF                   CIDADE     IBGE  POPU...
6   DF      UF      CIDADE     IBGE  POPULAÇÃO VALOR_T...
7   ES      UF                 CIDADE     IBGE  POPULA...
8   GO      UF                CIDADE     IBGE  POPULAÇ...
9   MA       UF                   CIDADE     IBGE  POP...
10  MG       UF                   CIDADE     IBGE  POP...
11  MS       UF       CIDADE     IBGE  POPULAÇÃO VALOR...
12  MT       UF                       CIDADE     IBGE ...
13  PA       UF                      CIDADE     IBGE  ...
14  PB       UF                    CIDADE     IBGE  PO...
15  PE       UF        CIDADE     IBGE  POPULAÇÃO VALO...
16  PI       UF                      CIDADE     IBGE  ...
17  PR       UF                    CIDADE     IBGE  PO...
18  RJ       UF                         CIDADE     IBG...
19  RN       UF              CIDADE     IBGE  POPULAÇÃ...
20  RO       UF         CIDADE     IBGE  POPULAÇÃO VAL...
21  RR       UF        CIDADE     IBGE  POPULAÇÃO VALO...
22  RS       UF                  CIDADE     IBGE  POPU...
23  SC       UF                CIDADE     IBGE  POPULA...
24  SE       UF                   CIDADE     IBGE  POP...
25  SP       UF                    CIDADE     IBGE  PO...
26  TO       UF                   CIDADE     IBGE  POP...

In [13]:
# Número de grupos
len(cidadesUF_1.groups)

27

In [14]:
ordenaUF = cidadesUF_1.size();cidadesUF_1

In [15]:
ordenaUF.sort_values(ascending= False)

UF
SP    35
BA    33
MG    28
MA    26
CE    26
PA    24
PI    18
PB    18
PR    17
PE    16
RS    16
RJ    15
GO    10
RN     9
AM     9
AP     6
SC     6
ES     4
TO     4
MT     4
SE     4
MS     3
RO     2
AL     2
DF     1
RR     1
AC     1
dtype: int64

In [61]:
# Ordena os grupos por ordem decrescente
ordenaUF.sort_values()

UF
AC     1
RR     1
DF     1
AL     2
RO     2
MS     3
SE     4
MT     4
TO     4
ES     4
SC     6
AP     6
AM     9
RN     9
GO    10
RJ    15
RS    16
PE    16
PR    17
PB    18
PI    18
PA    24
CE    26
MA    26
MG    28
BA    33
SP    35
dtype: int64

In [28]:
cidadesUF_2 = cidadesDigitais.groupby(['UF','STATUS'])

In [31]:
cidadesUF_2_df = pd.DataFrame(cidadesUF_2); cidadesUF_2_df

                     0                                                  1
0   (AC, Sem Previsão)     UF    CIDADE     IBGE  POPULAÇÃO VALOR_TOTA...
1   (AL, Sem Previsão)     UF              CIDADE     IBGE  POPULAÇÃO ...
2      (AM, Concluída)      UF      CIDADE     IBGE  POPULAÇÃO VALOR_T...
3   (AM, Sem Previsão)      UF             CIDADE     IBGE  POPULAÇÃO ...
4      (AP, Concluída)      UF          CIDADE     IBGE  POPULAÇÃO VAL...
5   (AP, Sem Previsão)      UF            CIDADE     IBGE  POPULAÇÃO V...
6      (BA, Concluída)      UF                CIDADE     IBGE  POPULAÇ...
7   (BA, Sem Previsão)      UF                     CIDADE     IBGE  PO...
8      (CE, Concluída)      UF                   CIDADE     IBGE  POPU...
9   (CE, Sem Previsão)      UF          CIDADE     IBGE  POPULAÇÃO VAL...
10     (DF, Concluída)      UF      CIDADE     IBGE  POPULAÇÃO VALOR_T...
11  (ES, Sem Previsão)      UF                 CIDADE     IBGE  POPULA...
12  (GO, Sem Previsão)      UF                CIDADE     IBGE  POPULAÇ...
13     (MA, Concluída)       UF               CIDADE     IBGE  POPULAÇ...
14  (MA, Sem Previsão)       UF                   CIDADE     IBGE  POP...
15     (MG, Concluída)       UF     CIDADE     IBGE  POPULAÇÃO VALOR_T...
16  (MG, Em andamento)       UF      CIDADE     IBGE  POPULAÇÃO VALOR_...
17  (MG, Sem Previsão)       UF                   CIDADE     IBGE  POP...
18  (MS, Sem Previsão)       UF       CIDADE     IBGE  POPULAÇÃO VALOR...
19  (MT, Sem Previsão)       UF                       CIDADE     IBGE ...
20     (PA, Concluída)       UF                 CIDADE     IBGE  POPUL...
21  (PA, Sem Previsão)       UF                      CIDADE     IBGE  ...
22     (PB, Concluída)       UF                    CIDADE     IBGE  PO...
23  (PB, Em andamento)       UF      CIDADE     IBGE  POPULAÇÃO VALOR_...
24  (PB, Sem Previsão)       UF               CIDADE     IBGE  POPULAÇ...
25     (PE, Concluída)       UF  CIDADE     IBGE  POPULAÇÃO VALOR_TOTA...
26  (PE, Sem Previsão)       UF        CIDADE     IBGE  POPULAÇÃO VALO...
27     (PI, Concluída)       UF              CIDADE     IBGE  POPULAÇÃ...
28  (PI, Sem Previsão)       UF                      CIDADE     IBGE  ...
29     (PR, Concluída)       UF                  CIDADE     IBGE  POPU...
30  (PR, Em andamento)       UF        CIDADE     IBGE  POPULAÇÃO VALO...
31  (PR, Sem Previsão)       UF                    CIDADE     IBGE  PO...
32     (RJ, Concluída)       UF                       CIDADE     IBGE ...
33  (RJ, Em andamento)       UF                         CIDADE     IBG...
34  (RJ, Sem Previsão)       UF                       CIDADE     IBGE ...
35     (RN, Concluída)       UF              CIDADE     IBGE  POPULAÇÃ...
36  (RN, Sem Previsão)       UF            CIDADE     IBGE  POPULAÇÃO ...
37  (RO, Sem Previsão)       UF         CIDADE     IBGE  POPULAÇÃO VAL...
38  (RR, Sem Previsão)       UF        CIDADE     IBGE  POPULAÇÃO VALO...
39     (RS, Concluída)       UF                  CIDADE     IBGE  POPU...
40  (RS, Em andamento)       UF        CIDADE     IBGE  POPULAÇÃO VALO...
41  (RS, Sem Previsão)       UF               CIDADE     IBGE  POPULAÇ...
42     (SC, Concluída)       UF   CIDADE     IBGE  POPULAÇÃO VALOR_TOT...
43  (SC, Sem Previsão)       UF                CIDADE     IBGE  POPULA...
44  (SE, Sem Previsão)       UF                   CIDADE     IBGE  POP...
45     (SP, Concluída)       UF               CIDADE     IBGE  POPULAÇ...
46  (SP, Em andamento)       UF       CIDADE     IBGE  POPULAÇÃO VALOR...
47  (SP, Sem Previsão)       UF                    CIDADE     IBGE  PO...
48  (TO, Sem Previsão)       UF                   CIDADE     IBGE  POP...

In [36]:
len(cidadesUF_2.groups)

49

In [41]:
total=cidadesUF_2.size();
total
total.sort_values(ascending=False)

UF  STATUS
SP  Sem Previsão    25
MG  Sem Previsão    25
MA  Sem Previsão    25
BA  Sem Previsão    24
PA  Sem Previsão    15
PE  Sem Previsão    15
PI  Sem Previsão    15
CE  Sem Previsão    15
RJ  Sem Previsão    12
CE  Concluída       11
RS  Sem Previsão    10
GO  Sem Previsão    10
PA  Concluída        9
PR  Sem Previsão     9
PB  Sem Previsão     9
BA  Concluída        9
SP  Concluída        8
RN  Sem Previsão     8
PR  Concluída        7
PB  Concluída        6
AM  Sem Previsão     6
SC  Sem Previsão     5
AP  Sem Previsão     5
ES  Sem Previsão     4
MT  Sem Previsão     4
TO  Sem Previsão     4
RS  Concluída        4
SE  Sem Previsão     4
PB  Em andamento     3
PI  Concluída        3
MS  Sem Previsão     3
AM  Concluída        3
AL  Sem Previsão     2
SP  Em andamento     2
RS  Em andamento     2
RO  Sem Previsão     2
RJ  Em andamento     2
MG  Concluída        2
RN  Concluída        1
PE  Concluída        1
DF  Concluída        1
RR  Sem Previsão     1
MA  Concluída        1
SC  Concluída        1
AP  Concluída        1
MG  Em andamento     1
RJ  Concluída        1
PR  Em andamento     1
AC  Sem Previsão     1
dtype: int64

In [13]:
# Total agrupado

UF  STATUS
AC  Sem Previsão     1
AL  Sem Previsão     2
AM  Concluída        3
    Sem Previsão     6
AP  Concluída        1
    Sem Previsão     5
BA  Concluída        9
    Sem Previsão    24
CE  Concluída       11
    Sem Previsão    15
DF  Concluída        1
ES  Sem Previsão     4
GO  Sem Previsão    10
MA  Concluída        1
    Sem Previsão    25
MG  Concluída        2
    Em andamento     1
    Sem Previsão    25
MS  Sem Previsão     3
MT  Sem Previsão     4
PA  Concluída        9
    Sem Previsão    15
PB  Concluída        6
    Em andamento     3
    Sem Previsão     9
PE  Concluída        1
    Sem Previsão    15
PI  Concluída        3
    Sem Previsão    15
PR  Concluída        7
    Em andamento     1
    Sem Previsão     9
RJ  Concluída        1
    Em andamento     2
    Sem Previsão    12
RN  Concluída        1
    Sem Previsão     8
RO  Sem Previsão     2
RR  Sem Previsão     1
RS  Concluída        4
    Em andamento     2
    Sem Previsão    10
SC  Concluída        1
    Sem Previsão     5
SE  Sem Previsão     4
SP  Concluída        8
    Em andamento     2
    Sem Previsão    25
TO  Sem Previsão     4
dtype: int64

In [66]:
total = cidadesUF_2.size()
total.sort_values(ascending=False)
total

UF  STATUS
AC  Sem Previsão     1
AL  Sem Previsão     2
AM  Concluída        3
    Sem Previsão     6
AP  Concluída        1
    Sem Previsão     5
BA  Concluída        9
    Sem Previsão    24
CE  Concluída       11
    Sem Previsão    15
DF  Concluída        1
ES  Sem Previsão     4
GO  Sem Previsão    10
MA  Concluída        1
    Sem Previsão    25
MG  Concluída        2
    Em andamento     1
    Sem Previsão    25
MS  Sem Previsão     3
MT  Sem Previsão     4
PA  Concluída        9
    Sem Previsão    15
PB  Concluída        6
    Em andamento     3
    Sem Previsão     9
PE  Concluída        1
    Sem Previsão    15
PI  Concluída        3
    Sem Previsão    15
PR  Concluída        7
    Em andamento     1
    Sem Previsão     9
RJ  Concluída        1
    Em andamento     2
    Sem Previsão    12
RN  Concluída        1
    Sem Previsão     8
RO  Sem Previsão     2
RR  Sem Previsão     1
RS  Concluída        4
    Em andamento     2
    Sem Previsão    10
SC  Concluída        1
    Sem Previsão     5
SE  Sem Previsão     4
SP  Concluída        8
    Em andamento     2
    Sem Previsão    25
TO  Sem Previsão     4
dtype: int64

In [67]:
cidadesDigitais.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,39484,"844.586,48",Sem Previsão,12,0

In [42]:
cidadesUF_3 = cidadesDigitais.set_index('STATUS')

In [43]:
# Aplicando Group By
cidadesUF_3= cidadesUF_3.groupby(level = 'STATUS')

In [44]:
cidadesUF_3.head()

,UF,CIDADE,IBGE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,PONTOS_ATENDIDOS,VALOR_INVESTIDO
STATUS,,,,,,,
Sem Previsão,AC,Tarauacá,1200609,38819,"484.547,53",8,0
Sem Previsão,AL,Delmiro Gouveia,2702405,51997,"1.169.381,70",43,0
Sem Previsão,AL,Estrela de Alagoas,2702553,18306,"527.206,83",39,0
Sem Previsão,AM,Autazes,1300300,37033,"1.171.151,92",51,0
Sem Previsão,AM,Benjamin Constant,1300607,39484,"844.586,48",12,0
Concluída,AM,Coari,1301209,83078,"814.954,75",27,0
Concluída,AM,Manacapuru,1302504,94175,"892.096,87",31,"763.009,30"
Concluída,AM,Manaquiri,1302553,28413,"636.682,15",21,0
Concluída,AP,Serra do Navio,1600055,4938,"590.073,15",21,"495.899,00"
Concluída,BA,Guanambi,2911709,85797,"533.416,18",15,"441.985,58"
Em andamento,MG,Nepomuceno,3144607,26897,"650.576,00",27,0
Em andamento,PB,Cabaceiras,2503100,5449,"355.867,86",15,0
Em andamento,PB,Esperança,2506004,32785,"643.482,51",23,0
Em andamento,PB,Itaporanga,2507002,24499,"649.011,44",23,0
Em andamento,PR,Bandeirantes,4102406,32639,"279.409,70",7,0

In [46]:


total3 = cidadesUF_3.size()
total3.sort_values(ascending=False)
total3

STATUS
Concluída        69
Em andamento     11
Sem Previsão    258
dtype: int64

In [47]:
cidadesUF_4 = cidadesDigitais.set_index(['UF', 'STATUS'])

In [48]:
cidadesUF_4

                                  CIDADE     IBGE  POPULAÇÃO  \
UF STATUS
AC Sem Previsão                 Tarauacá  1200609      38819
AL Sem Previsão          Delmiro Gouveia  2702405      51997
   Sem Previsão       Estrela de Alagoas  2702553      18306
AM Sem Previsão                  Autazes  1300300      37033
   Sem Previsão        Benjamin Constant  1300607      39484
...                                  ...      ...        ...
SP Sem Previsão     Vargem Grande do Sul  3556404      41807
TO Sem Previsão     Paraíso do Tocantins  1716109      49076
   Sem Previsão  Ponte Alta do Bom Jesus  1717800       4649
   Sem Previsão           Porto Nacional  1718204      52182
   Sem Previsão  São Miguel do Tocantins  1720200      11597

                VALOR_TOTAL_PREVISTO  PONTOS_ATENDIDOS VALOR_INVESTIDO
UF STATUS
AC Sem Previsão           484.547,53                 8               0
AL Sem Previsão         1.169.381,70                43               0
   Sem Previsão           527.206,83                39               0
AM Sem Previsão         1.171.151,92                51               0
   Sem Previsão           844.586,48                12               0
...                              ...               ...             ...
SP Sem Previsão         1.525.640,54                47               0
TO Sem Previsão         1.872.693,90                49               0
   Sem Previsão           251.266,44                 9       23.969,90
   Sem Previsão         1.101.168,76                61               0
   Sem Previsão           592.549,70                20               0

[338 rows x 6 columns]

In [56]:
cidadesUF_4 = cidadesDigitais.set_index(['UF', 'STATUS'])

In [57]:
cidadesUF_4 = cidadesUF_4.groupby(level = ["UF", "STATUS"])

In [52]:
cidadesUF_4

In [61]:
cidadesUf4_df = pd.DataFrame(cidadesUF_4); cidadesUf4_df

                     0                                                  1
0   (AC, Sem Previsão)                     CIDADE     IBGE  POPULAÇÃO ...
1   (AL, Sem Previsão)                               CIDADE     IBGE  ...
2      (AM, Concluída)                    CIDADE     IBGE  POPULAÇÃO V...
3   (AM, Sem Previsão)                              CIDADE     IBGE  P...
4      (AP, Concluída)                        CIDADE     IBGE  POPULAÇ...
5   (AP, Sem Previsão)                             CIDADE     IBGE  PO...
6      (BA, Concluída)                              CIDADE     IBGE  P...
7   (BA, Sem Previsão)                                      CIDADE    ...
8      (CE, Concluída)                                 CIDADE     IBGE...
9   (CE, Sem Previsão)                           CIDADE     IBGE  POPU...
10     (DF, Concluída)                    CIDADE     IBGE  POPULAÇÃO V...
11  (ES, Sem Previsão)                                  CIDADE     IBG...
12  (GO, Sem Previsão)                                 CIDADE     IBGE...
13     (MA, Concluída)                             CIDADE     IBGE  PO...
14  (MA, Sem Previsão)                                    CIDADE     I...
15     (MG, Concluída)                   CIDADE     IBGE  POPULAÇÃO VA...
16  (MG, Em andamento)                       CIDADE     IBGE  POPULAÇÃ...
17  (MG, Sem Previsão)                                    CIDADE     I...
18  (MS, Sem Previsão)                        CIDADE     IBGE  POPULAÇ...
19  (MT, Sem Previsão)                                        CIDADE  ...
20     (PA, Concluída)                               CIDADE     IBGE  ...
21  (PA, Sem Previsão)                                       CIDADE   ...
22     (PB, Concluída)                                  CIDADE     IBG...
23  (PB, Em andamento)                       CIDADE     IBGE  POPULAÇÃ...
24  (PB, Sem Previsão)                                CIDADE     IBGE ...
25     (PE, Concluída)                CIDADE     IBGE  POPULAÇÃO VALOR...
26  (PE, Sem Previsão)                         CIDADE     IBGE  POPULA...
27     (PI, Concluída)                            CIDADE     IBGE  POP...
28  (PI, Sem Previsão)                                       CIDADE   ...
29     (PR, Concluída)                                CIDADE     IBGE ...
30  (PR, Em andamento)                         CIDADE     IBGE  POPULA...
31  (PR, Sem Previsão)                                     CIDADE     ...
32     (RJ, Concluída)                                     CIDADE     ...
33  (RJ, Em andamento)                                          CIDADE...
34  (RJ, Sem Previsão)                                        CIDADE  ...
35     (RN, Concluída)                            CIDADE     IBGE  POP...
36  (RN, Sem Previsão)                             CIDADE     IBGE  PO...
37  (RO, Sem Previsão)                          CIDADE     IBGE  POPUL...
38  (RR, Sem Previsão)                         CIDADE     IBGE  POPULA...
39     (RS, Concluída)                                CIDADE     IBGE ...
40  (RS, Em andamento)                         CIDADE     IBGE  POPULA...
41  (RS, Sem Previsão)                                CIDADE     IBGE ...
42     (SC, Concluída)                 CIDADE     IBGE  POPULAÇÃO VALO...
43  (SC, Sem Previsão)                                 CIDADE     IBGE...
44  (SE, Sem Previsão)                                    CIDADE     I...
45     (SP, Concluída)                             CIDADE     IBGE  PO...
46  (SP, Em andamento)                        CIDADE     IBGE  POPULAÇ...
47  (SP, Sem Previsão)                                     CIDADE     ...
48  (TO, Sem Previsão)                                    CIDADE     I...

In [58]:
cidadesUF_4.sum()

                     IBGE  POPULAÇÃO  PONTOS_ATENDIDOS
UF STATUS
AC Sem Previsão   1200609      38819                 8
AL Sem Previsão   5404958      70303                82
AM Concluída      3906266     205666                79
   Sem Previsão   7807968     204136               167
AP Concluída      1600055       4938                21
   Sem Previsão   8002129     107938                81
BA Concluída     26292125    1171174               155
   Sem Previsão  69392013     532445               559
CE Concluída     24590427     658927               218
   Sem Previsão  34610391     427514               370
DF Concluída      5300108      32148                15
ES Sem Previsão  12810873     122164                94
GO Sem Previsão  52133974     166045               168
MA Concluída      2111201     174267                13
   Sem Previsão  52649406     571514               566
MG Concluída      6305309      18579                16
   Em andamento   3144607      26897                27
   Sem Previsão  78433329     465789               533
MS Sem Previsão  15017011     118431                94
MT Sem Previsão  20419667      77241                97
PA Concluída     13546544     620301               189
   Sem Previsão  22561116     470578               435
PB Concluída     15046929     127879                95
   Em andamento   7516106      62733                61
   Sem Previsão  22620036     111071               185
PE Concluída      2602001      37317                14
   Sem Previsão  38927114     342519               297
PI Concluída      6623570      37987                45
   Sem Previsão  33105147     187556               213
PR Concluída     25471628     418078               134
   Em andamento   4102406      32639                 7
   Sem Previsão  35739641     284252               247
RJ Concluída      3301801      13626                11
   Em andamento   6607858     167465                35
   Sem Previsão  38446111     413049               312
RN Concluída      2412104       6218                13
   Sem Previsão  19254330      77814               145
RO Sem Previsão   2200558      84470                39
RR Sem Previsão   1400472      27288                21
RS Concluída     17260455     107356                73
   Em andamento   8617106      40954                30
   Sem Previsão  43108016     300041               265
SC Concluída      4209003      29008                18
   Sem Previsão  21045326     187416                90
SE Sem Previsão  10727418     187455               107
SP Concluída     28230938     235299               173
   Em andamento   7024509      62857                37
   Sem Previsão  87158690     898779               810
TO Sem Previsão   6872313     117504               139

In [103]:
cidadesUF_4.aggregate(np.sum)

                 POPULAÇÃO  PONTOS_ATENDIDOS
UF STATUS
AC Sem Previsão      38819                 8
AL Sem Previsão      70303                82
AM Concluída        205666                79
   Sem Previsão     204136               167
AP Concluída          4938                21
   Sem Previsão     107938                81
BA Concluída       1171174               155
   Sem Previsão     532445               559
CE Concluída        658927               218
   Sem Previsão     427514               370
DF Concluída         32148                15
ES Sem Previsão     122164                94
GO Sem Previsão     166045               168
MA Concluída        174267                13
   Sem Previsão     571514               566
MG Concluída         18579                16
   Em andamento      26897                27
   Sem Previsão     465789               533
MS Sem Previsão     118431                94
MT Sem Previsão      77241                97
PA Concluída        620301               189
   Sem Previsão     470578               435
PB Concluída        127879                95
   Em andamento      62733                61
   Sem Previsão     111071               185
PE Concluída         37317                14
   Sem Previsão     342519               297
PI Concluída         37987                45
   Sem Previsão     187556               213
PR Concluída        418078               134
   Em andamento      32639                 7
   Sem Previsão     284252               247
RJ Concluída         13626                11
   Em andamento     167465                35
   Sem Previsão     413049               312
RN Concluída          6218                13
   Sem Previsão      77814               145
RO Sem Previsão      84470                39
RR Sem Previsão      27288                21
RS Concluída        107356                73
   Em andamento      40954                30
   Sem Previsão     300041               265
SC Concluída         29008                18
   Sem Previsão     187416                90
SE Sem Previsão     187455               107
SP Concluída        235299               173
   Em andamento      62857                37
   Sem Previsão     898779               810
TO Sem Previsão     117504               139

In [104]:
cidadesUF_4.aggregate([np.sum, np.mean, np.size])

                POPULAÇÃO                     PONTOS_ATENDIDOS
                      sum           mean size              sum       mean size
UF STATUS
AC Sem Previsão     38819   38819.000000    1                8   8.000000    1
AL Sem Previsão     70303   35151.500000    2               82  41.000000    2
AM Concluída       205666   68555.333333    3               79  26.333333    3
   Sem Previsão    204136   34022.666667    6              167  27.833333    6
AP Concluída         4938    4938.000000    1               21  21.000000    1
   Sem Previsão    107938   21587.600000    5               81  16.200000    5
BA Concluída      1171174  130130.444444    9              155  17.222222    9
   Sem Previsão    532445   22185.208333   24              559  23.291667   24
CE Concluída       658927   59902.454545   11              218  19.818182   11
   Sem Previsão    427514   28500.933333   15              370  24.666667   15
DF Concluída        32148   32148.000000    1               15  15.000000    1
ES Sem Previsão    122164   30541.000000    4               94  23.500000    4
GO Sem Previsão    166045   16604.500000   10              168  16.800000   10
MA Concluída       174267  174267.000000    1               13  13.000000    1
   Sem Previsão    571514   22860.560000   25              566  22.640000   25
MG Concluída        18579    9289.500000    2               16   8.000000    2
   Em andamento     26897   26897.000000    1               27  27.000000    1
   Sem Previsão    465789   18631.560000   25              533  21.320000   25
MS Sem Previsão    118431   39477.000000    3               94  31.333333    3
MT Sem Previsão     77241   19310.250000    4               97  24.250000    4
PA Concluída       620301   68922.333333    9              189  21.000000    9
   Sem Previsão    470578   31371.866667   15              435  29.000000   15
PB Concluída       127879   21313.166667    6               95  15.833333    6
   Em andamento     62733   20911.000000    3               61  20.333333    3
   Sem Previsão    111071   12341.222222    9              185  20.555556    9
PE Concluída        37317   37317.000000    1               14  14.000000    1
   Sem Previsão    342519   22834.600000   15              297  19.800000   15
PI Concluída        37987   12662.333333    3               45  15.000000    3
   Sem Previsão    187556   12503.733333   15              213  14.200000   15
PR Concluída       418078   59725.428571    7              134  19.142857    7
   Em andamento     32639   32639.000000    1                7   7.000000    1
   Sem Previsão    284252   31583.555556    9              247  27.444444    9
RJ Concluída        13626   13626.000000    1               11  11.000000    1
   Em andamento    167465   83732.500000    2               35  17.500000    2
   Sem Previsão    413049   34420.750000   12              312  26.000000   12
RN Concluída         6218    6218.000000    1               13  13.000000    1
   Sem Previsão     77814    9726.750000    8              145  18.125000    8
RO Sem Previsão     84470   42235.000000    2               39  19.500000    2
RR Sem Previsão     27288   27288.000000    1               21  21.000000    1
RS Concluída       107356   26839.000000    4               73  18.250000    4
   Em andamento     40954   20477.000000    2               30  15.000000    2
   Sem Previsão    300041   30004.100000   10              265  26.500000   10
SC Concluída        29008   29008.000000    1               18  18.000000    1
   Sem Previsão    187416   37483.200000    5               90  18.000000    5
SE Sem Previsão    187455   46863.750000    4              107  26.750000    4
SP Concluída       235299   29412.375000    8              173  21.625000    8
   Em andamento     62857   31428.500000    2               37  18.500000    2
   Sem Previsão    898779   35951.160000   25              810  32.400000   25
TO Sem Previsão    117504   29376.000000    4              139  34.750000    4

In [27]:
cidadesDigitais.head(3)

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0

In [106]:
cidadesUF_5 = cidadesDigitais.set_index(['STATUS', 'CIDADE', "VALOR_TOTAL_PREVISTO"])

In [109]:
cidadesUF_5 = cidadesUF_5.groupby(level=['STATUS', 'VALOR_TOTAL_PREVISTO'])

In [111]:
cidadesDigitais.head(3)

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0

In [112]:
cidadesUF_5.sum()

                                   POPULAÇÃO  PONTOS_ATENDIDOS
STATUS       VALOR_TOTAL_PREVISTO
Concluída    1.023.839,75             107010                34
             1.024.440,40              78976                35
             234.752,50                37124                29
             266.802,12                10650                 6
             270.085,77                 3597                 6
...                                      ...               ...
Sem Previsão 945.054,68                36329                18
             945.609,08                40378                34
             978.516,72                24993                23
             982.422,53                35240                37
             998.180,59                26589                30

[331 rows x 2 columns]

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>